# Generated by Django 5.2.16 on 2026-07-16 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_value', models.CharField(max_length=16)),
                ('event', models.CharField(max_length=4)),
                ('stage', models.CharField(max_length=32)),
                ('doubles', models.BooleanField(default=False)),
                ('size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['tournament', 'event'],
            },
        ),
        migrations.CreateModel(
            name='RawCache',
            fields=[
                ('url', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('fetched_utc', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['-fetched_utc'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255)),
                ('series_id', models.IntegerField(blank=True, null=True)),
                ('prize_money', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=16)),
                ('event', models.CharField(max_length=4)),
                ('round_name', models.CharField(max_length=16)),
                ('round_order', models.IntegerField(default=0)),
                ('match_time_utc', models.DateTimeField(blank=True, null=True)),
                ('duration_min', models.IntegerField(blank=True, null=True)),
                ('court_name', models.CharField(blank=True, max_length=64)),
                ('score_status', models.CharField(max_length=32)),
                ('reliability', models.IntegerField(blank=True, null=True)),
                ('winner_side', models.IntegerField(blank=True, null=True)),
                ('side1_seed', models.CharField(blank=True, max_length=8)),
                ('side2_seed', models.CharField(blank=True, max_length=8)),
                ('scoring_format', models.CharField(blank=True, max_length=16)),
                ('rating_excluded', models.BooleanField(default=False)),
                ('draw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='ingest.draw')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='ingest.tournament')),
            ],
            options={
                'ordering': ['match_time_utc', 'round_order', 'match_id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_display', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('name_short', models.CharField(blank=True, max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=8)),
                ('avatar_url', models.URLField(blank=True, max_length=512)),
                ('dob', models.DateField(blank=True, null=True)),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('plays', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'ordering': ['name_display'],
                'indexes': [models.Index(fields=['country_code'], name='ingest_play_country_f77dcc_idx')],
            },
        ),
        migrations.AddField(
            model_name='draw',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='ingest.tournament'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_no', models.IntegerField()),
                ('side1_points', models.IntegerField()),
                ('side2_points', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='ingest.match')),
            ],
            options={
                'ordering': ['match', 'game_no'],
                'unique_together': {('match', 'game_no')},
            },
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup', to='ingest.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingest.player')),
            ],
            options={
                'ordering': ['match', 'side'],
                'unique_together': {('match', 'side', 'player')},
            },
        ),
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=4)),
                ('mu', models.FloatField()),
                ('rd', models.FloatField()),
                ('sigma', models.FloatField()),
                ('matches_played', models.IntegerField(default=0)),
                ('last_match_utc', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ingest.player')),
            ],
            options={
                'ordering': ['event', '-mu'],
                'unique_together': {('player', 'event')},
            },
        ),
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=4)),
                ('mu_before', models.FloatField()),
                ('mu_after', models.FloatField()),
                ('rd_before', models.FloatField()),
                ('rd_after', models.FloatField()),
                ('delta', models.FloatField()),
                ('applied_utc', models.DateTimeField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to='ingest.player')),
            ],
            options={
                'ordering': ['applied_utc', 'match_id'],
                'indexes': [models.Index(fields=['player', 'event', 'applied_utc'], name='ingest_rati_player__b11482_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'event'], name='ingest_matc_tournam_4c5425_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['event', 'match_time_utc'], name='ingest_matc_event_8a9394_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='draw',
            unique_together={('tournament', 'draw_value')},
        ),
    ]
