# Generated by Django 5.2.16 on 2026-07-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_alter_ratinghistory_applied_utc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
