# Generated by Django 5.2.16 on 2026-07-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_alter_tournament_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrating',
            name='peak_mu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerrating',
            name='peak_rd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerrating',
            name='peak_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
