# Generated by Django 5.2.16 on 2026-07-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0004_playerrating_peak_mu_playerrating_peak_rd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=8)),
                ('matches_together', models.IntegerField(default=0)),
                ('wins_together', models.IntegerField(default=0)),
                ('combined_mu', models.FloatField()),
                ('combined_rd', models.FloatField()),
                ('last_match_utc', models.DateTimeField(blank=True, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_p1', to='ingest.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_p2', to='ingest.player')),
            ],
            options={
                'ordering': ['event', '-combined_mu'],
                'indexes': [models.Index(fields=['event', '-combined_mu'], name='ingest_part_event_de8297_idx')],
                'unique_together': {('event', 'player1', 'player2')},
            },
        ),
    ]
