# Generated by Django 5.2.16 on 2026-07-17 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_player_gender_partnership'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStatistics',
            fields=[
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='ingest.match')),
                ('team1_rallies_won', models.IntegerField(blank=True, null=True)),
                ('team1_rallies_played', models.IntegerField(blank=True, null=True)),
                ('team2_rallies_won', models.IntegerField(blank=True, null=True)),
                ('team2_rallies_played', models.IntegerField(blank=True, null=True)),
                ('team1_consecutive_points', models.IntegerField(blank=True, null=True)),
                ('team2_consecutive_points', models.IntegerField(blank=True, null=True)),
                ('team1_game_points', models.IntegerField(blank=True, null=True)),
                ('team2_game_points', models.IntegerField(blank=True, null=True)),
                ('duration_min', models.IntegerField(blank=True, null=True)),
                ('point_progression', models.JSONField(blank=True, null=True)),
                ('fetched_utc', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeedRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=8)),
                ('rank', models.IntegerField()),
                ('observed_date', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_ranks', to='ingest.player')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'rank'], name='ingest_play_event_b5c87f_idx')],
                'unique_together': {('player', 'event')},
            },
        ),
    ]
