# Generated by Django 5.2.16 on 2026-07-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0006_matchstatistics_playerseedrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='combined_peak_mu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='combined_peak_rd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
