# Generated by Django 5.2.16 on 2026-07-18 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0007_partnership_combined_peak_mu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=8)),
                ('net_delta', models.FloatField()),
                ('matches', models.IntegerField()),
                ('mu_start', models.FloatField()),
                ('mu_end', models.FloatField()),
                ('best_delta', models.FloatField(blank=True, null=True)),
                ('best_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_perfs', to='ingest.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.tournament')),
            ],
            options={
                'indexes': [models.Index(fields=['-net_delta'], name='ingest_tour_net_del_e46518_idx'), models.Index(fields=['event', '-net_delta'], name='ingest_tour_event_755773_idx')],
                'unique_together': {('player', 'event', 'tournament')},
            },
        ),
    ]
