# Generated by Django 5.2.16 on 2026-07-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0008_tournamentperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentperformance',
            name='rd_start',
            field=models.FloatField(default=350.0),
        ),
    ]
