# Generated by Django 5.2.16 on 2026-07-18 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0009_tournamentperformance_rd_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentperformance',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_perfs_as_partner', to='ingest.player'),
        ),
    ]
