# Generated by Django 5.2.16 on 2026-07-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0010_tournamentperformance_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentperformance',
            name='perf_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
