# Generated by Django 5.2.16 on 2026-07-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0011_tournamentperformance_perf_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupPowerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=8)),
                ('year', models.IntegerField()),
                ('power', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['cup', 'year'], name='ingest_cupp_cup_324824_idx')],
                'unique_together': {('cup', 'country', 'year')},
            },
        ),
    ]
