# Generated by Django 5.2.16 on 2026-07-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0012_cuppowerhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstatistics',
            name='max_comeback',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
