# Generated by Django 5.2.16 on 2026-07-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0013_matchstatistics_max_comeback'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='source_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='wiki_title',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
