# Generated by Django 5.2.16 on 2026-07-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0014_match_source_key_player_wiki_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconcileDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_title', models.CharField(max_length=255, unique=True)),
                ('decision', models.CharField(max_length=16)),
                ('target_player_id', models.IntegerField(blank=True, null=True)),
                ('created_utc', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
