# Generated by Django 5.2.16 on 2026-07-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0015_reconciledecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birth_place',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='player',
            name='current_residence',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='player',
            name='languages',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='player',
            name='prize_money',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
