# Generated by Django 5.2.16 on 2026-07-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0016_player_birth_place_player_current_residence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='logo_url',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
