# Generated by Django 5.2.16 on 2026-07-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0017_tournament_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=8)),
                ('bucket', models.IntegerField()),
                ('n', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('prob_sum', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['event', 'bucket'],
                'unique_together': {('event', 'bucket')},
            },
        ),
    ]
