# Generated by Django 5.2.16 on 2026-07-23 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0018_calibrationbin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClutchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=8)),
                ('deciders_played', models.IntegerField(default=0)),
                ('deciders_won', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clutch_stats', to='ingest.player')),
            ],
            options={
                'indexes': [models.Index(fields=['event', '-deciders_played'], name='ingest_clut_event_a173a4_idx')],
                'unique_together': {('player', 'event')},
            },
        ),
    ]
