# Generated by Django 5.2.16 on 2026-07-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0019_clutchstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=8)),
                ('year', models.IntegerField()),
                ('power', models.FloatField()),
                ('players', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'year'], name='ingest_nati_event_3e21cd_idx')],
                'unique_together': {('event', 'country', 'year')},
            },
        ),
    ]
