# Generated by Django 5.2.16 on 2026-07-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0020_nationyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrating',
            name='volatility',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
