# Generated by Django 5.2.16 on 2026-07-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0021_playerrating_volatility'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='perf_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='synergy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
