# Generated by Django 5.2.16 on 2026-07-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0022_partnership_perf_rating_partnership_synergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='side1_country',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='side2_country',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
