# Generated by Django 5.2.17 on 2026-10-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0023_match_side1_country_match_side2_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrating',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerrating',
            name='rank_gender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerrating',
            name='rank_prev',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerrating',
            name='rank_prev_gender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
