# Generated by Django 5.2.17 on 2026-10-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0024_playerrating_rank'),
    ]

    # State-only: the column stays NOT NULL text; the "" default is applied by
    # Django, so there is nothing to change in the database. (A real AlterField
    # would rebuild the table — copying ~3 GB of legacy bodies on SQLite.)
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='rawcache',
                    name='body',
                    field=models.TextField(blank=True, default=''),
                ),
            ],
        ),
    ]
