# Generated by Django 5.2.17 on 2026-10-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0025_rawcache_body_on_disk'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrating',
            name='form',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='playerrating',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerrating',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentperformance',
            name='achievement',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddIndex(
            model_name='playerrating',
            index=models.Index(fields=['event', 'rank'], name='ingest_play_event_89a8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='playerrating',
            index=models.Index(fields=['event', 'rank_gender'], name='ingest_play_event_7fff54_idx'),
        ),
        migrations.AddIndex(
            model_name='ratinghistory',
            index=models.Index(condition=models.Q(('delta__gte', 30)), fields=['-delta'], name='rh_upset_delta_idx'),
        ),
        migrations.AddIndex(
            model_name='ratinghistory',
            index=models.Index(condition=models.Q(('delta__gte', 30)), fields=['event', '-delta'], name='rh_upset_event_delta_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentperformance',
            index=models.Index(fields=['-perf_rating'], name='ingest_tour_perf_ra_3a0229_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentperformance',
            index=models.Index(fields=['event', '-perf_rating'], name='ingest_tour_event_9a5a8f_idx'),
        ),
    ]
