# Generated by Django 5.2.17 on 2026-10-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0026_precomputed_board_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('updated_utc', models.DateTimeField()),
                ('latest_match_utc', models.DateTimeField(blank=True, null=True)),
                ('active_cutoff', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
