# Generated by Django 5.2.17 on 2026-10-04 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0027_dataversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsFetchJob',
            fields=[
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats_job', serialize=False, to='ingest.match')),
                ('status', models.CharField(default='pending', max_length=12)),
                ('attempts', models.IntegerField(default=0)),
                ('updated_utc', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'updated_utc'], name='ingest_stat_status_5a71a6_idx')],
            },
        ),
    ]
