# Generated by Django 5.2.17 on 2026-10-04 10:20

from django.db import migrations, models


def fill_match_counts(apps, schema_editor):
    Match = apps.get_model("ingest", "Match")
    Tournament = apps.get_model("ingest", "Tournament")
    counts = dict(
        Match.objects.order_by().values_list("tournament_id")
        .annotate(n=models.Count("match_id"))
    )
    rows = list(Tournament.objects.only("tournament_id"))
    for t in rows:
        t.match_count = counts.get(t.tournament_id, 0)
    Tournament.objects.bulk_update(rows, ["match_count"], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0028_statsfetchjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='match_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['match_count', '-start_date'], name='ingest_tour_match_c_e964ae_idx'),
        ),
        migrations.RunPython(fill_match_counts, migrations.RunPython.noop),
    ]
