# Generated by Django 5.2.17 on 2026-10-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0029_tournament_match_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
                ('mode', models.CharField(blank=True, max_length=16)),
                ('steps_total', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(null=True)),
                ('message', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
