# Generated by Django 5.2.17 on 2026-10-04 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0030_refreshjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTies',
            fields=[
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ties', serialize=False, to='ingest.tournament')),
                ('payload', models.JSONField()),
            ],
        ),
    ]
