# Generated by Django 5.2.17 on 2026-10-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0031_tournamentties'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatedPeriod',
            fields=[
                ('tournament_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=40)),
                ('start_ts', models.DateTimeField(blank=True, null=True)),
                ('start_round', models.IntegerField(default=0)),
                ('start_match', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RatingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_hash', models.CharField(max_length=40)),
                ('seeds_hash', models.CharField(max_length=40)),
                ('updated_utc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RatingUndo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField(db_index=True)),
                ('player_id', models.IntegerField()),
                ('event', models.CharField(max_length=8)),
                ('existed', models.BooleanField(default=True)),
                ('mu', models.FloatField(null=True)),
                ('rd', models.FloatField(null=True)),
                ('sigma', models.FloatField(null=True)),
                ('matches_played', models.IntegerField(default=0)),
                ('last_match_utc', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
