# Generated by Django 5.2.17 on 2026-10-04 11:13

import django.db.models.expressions
from django.db import migrations, models

# Name search is `icontains` (LIKE '%q%'), which no B-tree index can serve.
# On Postgres a trigram GIN index can; SQLite has no equivalent, so skip there.
TRGM = [
    ("ingest_player", "name_display", "player_name_trgm_idx"),
    ("ingest_tournament", "name", "tournament_name_trgm_idx"),
]


def add_trigram_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    for table, column, name in TRGM:
        schema_editor.execute(
            f'CREATE INDEX IF NOT EXISTS {name} ON {table} USING gin ("{column}" gin_trgm_ops)'
        )


def drop_trigram_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for _, _, name in TRGM:
        schema_editor.execute(f"DROP INDEX IF EXISTS {name}")


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0032_incremental_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='rating',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('combined_mu'), '-', django.db.models.expressions.CombinedExpression(models.Value(2.0), '*', models.F('combined_rd'))), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='playerrating',
            name='rating',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('mu'), '-', django.db.models.expressions.CombinedExpression(models.Value(2.0), '*', models.F('rd'))), output_field=models.FloatField()),
        ),
        migrations.AddIndex(
            model_name='partnership',
            index=models.Index(fields=['event', '-rating'], name='ingest_part_event_7a3478_idx'),
        ),
        migrations.AddIndex(
            model_name='playerrating',
            index=models.Index(fields=['event', '-rating'], name='ingest_play_event_a17251_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentperformance',
            index=models.Index(condition=models.Q(('rd_start__lte', 130)), fields=['-net_delta'], name='tp_settled_gains_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentperformance',
            index=models.Index(condition=models.Q(('rd_start__lte', 130)), fields=['event', '-net_delta'], name='tp_settled_event_gains_idx'),
        ),
        migrations.RunPython(add_trigram_indexes, drop_trigram_indexes),
    ]
