# Generated by Django 5.2.17 on 2026-10-04 11:36

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0033_stored_ratings_and_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmoothedRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=8)),
                ('year', models.IntegerField()),
                ('mu', models.FloatField()),
                ('rd', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='playerrating',
            name='alltime_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerrating',
            name='alltime_mu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerrating',
            name='alltime_rd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smoothedrating',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smoothed', to='ingest.player'),
        ),
        migrations.AddField(
            model_name='playerrating',
            name='alltime_rating',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('alltime_mu'), '-', django.db.models.expressions.CombinedExpression(models.Value(2.0), '*', models.F('alltime_rd'))), output_field=models.FloatField()),
        ),
        migrations.AddIndex(
            model_name='playerrating',
            index=models.Index(fields=['event', '-alltime_rating'], name='ingest_play_event_6400dd_idx'),
        ),
        migrations.AddIndex(
            model_name='smoothedrating',
            index=models.Index(fields=['event', 'year'], name='ingest_smoo_event_e4f397_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='smoothedrating',
            unique_together={('player', 'event', 'year')},
        ),
    ]
